export const hostedSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL COLLATE NOCASE UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('workspace_owner','admin','technician','client_admin','client_user','read_only')),
    password_hash TEXT NOT NULL,
    kdf_salt TEXT NOT NULL,
    wrapped_key_nonce TEXT NOT NULL,
    wrapped_key_ciphertext TEXT NOT NULL,
    mfa_secret_nonce TEXT NOT NULL,
    mfa_secret_ciphertext TEXT NOT NULL,
    mfa_enabled INTEGER NOT NULL DEFAULT 0 CHECK (mfa_enabled IN (0,1)),
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TEXT,
    disabled_at TEXT,
    must_change_password INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0,1)),
    welcome_sent_at TEXT,
    welcome_send_count INTEGER NOT NULL DEFAULT 0,
    last_login_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS recovery_codes (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL,
    used_at TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    csrf_token TEXT NOT NULL,
    vault_key_nonce TEXT NOT NULL,
    vault_key_ciphertext TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    step_up_until TEXT,
    step_up_failed_count INTEGER NOT NULL DEFAULT 0,
    ip_hash TEXT,
    user_agent TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS login_challenges (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('login','enrollment')),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vault_key_nonce TEXT NOT NULL,
    vault_key_ciphertext TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT,
    notes TEXT NOT NULL DEFAULT '',
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS locations (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS systems (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    collection TEXT NOT NULL CHECK (collection IN ('network','av_systems','voip','access_control','remote_access','software','websites_accounts','general')),
    manufacturer TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    network_address TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS assets (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    system_id TEXT REFERENCES systems(id) ON DELETE SET NULL,
    asset_type TEXT NOT NULL CHECK (asset_type IN ('device','software','website_account')),
    name TEXT NOT NULL,
    vendor TEXT NOT NULL DEFAULT '',
    version_or_model TEXT NOT NULL DEFAULT '',
    identifier TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS credentials (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    location_id TEXT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    system_id TEXT REFERENCES systems(id) ON DELETE SET NULL,
    collection TEXT NOT NULL CHECK (collection IN ('network','av_systems','voip','access_control','remote_access','software','websites_accounts','general')),
    name TEXT NOT NULL,
    url TEXT NOT NULL DEFAULT '',
    secret_nonce TEXT NOT NULL,
    secret_ciphertext TEXT NOT NULL,
    last_verified_at TEXT,
    expires_at TEXT,
    created_by TEXT NOT NULL REFERENCES users(id),
    updated_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS permissions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scope_key TEXT NOT NULL,
    client_id TEXT REFERENCES clients(id) ON DELETE CASCADE,
    location_id TEXT REFERENCES locations(id) ON DELETE CASCADE,
    collection TEXT CHECK (collection IS NULL OR collection IN ('network','av_systems','voip','access_control','remote_access','software','websites_accounts','general')),
    can_view INTEGER NOT NULL DEFAULT 0 CHECK (can_view IN (0,1)),
    can_manage INTEGER NOT NULL DEFAULT 0 CHECK (can_manage IN (0,1)),
    can_reveal INTEGER NOT NULL DEFAULT 0 CHECK (can_reveal IN (0,1)),
    can_export INTEGER NOT NULL DEFAULT 0 CHECK (can_export IN (0,1)),
    created_by TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(user_id, scope_key)
  )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    occurred_at TEXT NOT NULL,
    actor_user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    client_id TEXT REFERENCES clients(id) ON DELETE SET NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('success','failure','blocked')),
    ip_hash TEXT,
    user_agent TEXT,
    detail_json TEXT NOT NULL DEFAULT '{}',
    previous_hash TEXT NOT NULL,
    entry_hash TEXT NOT NULL UNIQUE
  )`,
  `CREATE TRIGGER IF NOT EXISTS audit_log_no_update BEFORE UPDATE ON audit_log BEGIN SELECT RAISE(ABORT, 'audit log entries are immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS audit_log_no_delete BEFORE DELETE ON audit_log BEGIN SELECT RAISE(ABORT, 'audit log entries are immutable'); END`,
  `CREATE INDEX IF NOT EXISTS idx_locations_client_id ON locations(client_id)`,
  `CREATE INDEX IF NOT EXISTS idx_systems_location_id ON systems(location_id)`,
  `CREATE INDEX IF NOT EXISTS idx_systems_client_collection ON systems(client_id, collection)`,
  `CREATE INDEX IF NOT EXISTS idx_assets_location_type ON assets(location_id, asset_type)`,
  `CREATE INDEX IF NOT EXISTS idx_credentials_location_collection ON credentials(location_id, collection)`,
  `CREATE INDEX IF NOT EXISTS idx_credentials_system_id ON credentials(system_id)`,
  `CREATE INDEX IF NOT EXISTS idx_permissions_user_scope ON permissions(user_id, client_id, location_id, collection)`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_login_challenges_expires_at ON login_challenges(expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_occurred_at ON audit_log(occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_actor_user ON audit_log(actor_user_id, occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_recovery_codes_user_unused ON recovery_codes(user_id, used_at)`,
] as const;
